name: "Extract Package Name"

inputs:
  text:
    required: true

outputs:
  package:
    description: "The package name extracted from the PR description"
    value: ${{ steps.extract-package.outputs.package }}

runs:
  using: composite
  steps:
    - id: extract-package
      shell: bash
      env:
        TEXT: ${{ inputs.text }}
      run: |
        package=$(echo "$TEXT" | sed -n '/### Package/,$p' | grep - | sed 's/- //' | tr -d '\n\r' | sed 's/ //g' || echo "")
        echo "package=$package" >> $GITHUB_OUTPUT
