name: 'Manage QA Slot'
description: 'It creates, updates or remove a QA slot'

inputs:
  command-name:
    description: 'Command Name'
    required: true
  command-token:
    description: 'Command Token'
    required: true
  command-args:
    description: 'Command arguments'
    required: true

runs:
  using: composite
  steps:
    - name: Request the service to execute the command in Tools Endpoint
      run: |
        curl --location "$SERVICE_URL" \
              --header 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode "user_id=$PARAM_USER_ID" \
              --data-urlencode "token=$PARAM_TOKEN" \
              --data-urlencode "command=$PARAM_COMMAND" \
              --data-urlencode "text=$PARAM_TEXT"
      shell: bash
      env:
        SERVICE_URL: https://c83a-24-201-230-155.ngrok-free.app/test
        PARAM_USER_ID: "D03JNAHRFNX" # Nico :P
        PARAM_COMMAND: ${{ inputs.command-name }}
        PARAM_TEXT: ${{ inputs.command-args }}
        PARAM_TOKEN: ${{ inputs.command-token }} # hard-coded token in https://github.com/TrackTik/tool-endpoints
