name: Create QA Slot
run-name: Create the QA environment for this version 🔬

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  create-qa-slot:
    if: contains(github.event.pull_request.labels.*.name, 'QA Required') && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Normalizes branch name
        id: normalize-branch-name
        run: echo "normalized-branch-name=$(echo ${{ github.head_ref }} | tr -d '-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Launch AWX template to create QA environment
        uses: ./.github/actions/launch-awx-template
        with:
          job-template-id: 1
          domain: ${{ secrets.AWX_DOMAIN }}
          username: ${{ secrets.AWX_USER }}
          password: ${{ secrets.AWX_PASSWORD }}
          extra-vars: '{
              "extra_vars":{
                "branch_name": "${{ steps.normalize-branch-name.outputs.normalized-branch-name }}",
                "branch_name_unsanitized": "${{ github.head_ref }}",
                "is_securitas": "no"
              }
            }'
# TODO: support integration packages and securitas environments
