name: Create QA Slot
run-name: Create the QA environment for this version 🔬

on:
  pull_request:
    types: [labeled]

jobs:
  create-qa-slot:
    if: contains(github.event.pull_request.labels.*.name, 'enhancement') && !github.event.pull_request.draft
    name: Create QA Slot
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - id: normalize-branch-name
        uses: ./.github/actions/normalize-branch-name
        with:
          branch_name: ${{ github.head_ref }}

      - id: read-integration-package
        uses: ./.github/actions/read-integration-package
        with:
          text: ${{ github.event.pull_request.body }}

      - name: Check if integration package is customer
        id: check-is-customer
        run: |
          if [[ "${{ steps.read-integration-package.outputs.integration-package }}" == *"customer"* ]]; then
            echo "is_customer=yes" >> $GITHUB_OUTPUT
          else
            echo "is_customer=no" >> $GITHUB_OUTPUT
          fi

      - name: Launch AWX template to create QA environment
        uses: ./.github/actions/launch-awx-template
        with:
          job-template-id: 1
          domain: ${{ secrets.AWX_DOMAIN }}
          username: ${{ secrets.AWX_USER }}
          password: ${{ secrets.AWX_PASSWORD }}
          extra-vars: '{
            "extra_vars":{
            "branch_name": "${{ steps.normalize-branch-name.outputs.normalized-branch-name }}",
            "branch_name_unsanitized": "${{ github.head_ref }}",
            "integration_package_name": "${{ steps.read-integration-package.outputs.integration-package }}",
            "is_customer": "${{ steps.check-is-customer.outputs.is_customer }}"
            }
            }'
