name: Create QA Slot
run-name: Create a QA environment for this version 🔬

on:
  pull_request:
    types: [opened, labeled, ready_for_review]

env:
  SERVICE_URL: https://tool-endpoint.staffr.net/tools-bot/command
  PARAM_TOKEN: xjvx6fLLa87HRlsM6ZDSmGSg # hard-coded token in https://github.com/TrackTik/tool-endpoints
  PARAM_COMMAND: "/qadeploy"
  PARAM_TEXT: ${{ github.head_ref }}
  # FIXME: AWX will flag the job as failed even though the slot is created
  PARAM_USER_ID: "" # N/A, when triggered via Slack services notifies the user

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Request the service to create a QA environment for this version
        if: contains(github.event.pull_request.labels.*.name, 'QA Required') && !github.event.pull_request.draft
        run: |
          curl --location "$SERVICE_URL" \
               --header 'Content-Type: application/x-www-form-urlencoded' \
               --data-urlencode "user_id=$PARAM_USER_ID" \
               --data-urlencode "token=$PARAM_TOKEN" \
               --data-urlencode "command=$PARAM_COMMAND" \
               --data-urlencode "text=$PARAM_TEXT"