name: Remove QA Slot
run-name: Remove the QA environment for this version 🔬

on:
  pull_request:
    types: [closed]

jobs:
  remove-qa-slot:
    if: contains(github.event.pull_request.labels.*.name, 'enhancement') && !github.event.pull_request.draft
    name: Remove QA Slot
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - id: normalize-branch-name
        uses: ./.github/actions/normalize-branch-name
        with:
          branch_name: ${{ github.head_ref }}

      - name: Launch AWX template to remove QA environment
        uses: ./.github/actions/launch-awx-template
        with:
          job-template-id: 3
          domain: ${{ secrets.AWX_DOMAIN }}
          username: ${{ secrets.AWX_USER }}
          password: ${{ secrets.AWX_PASSWORD }}
          extra-vars: '{"extra_vars":{"branch_name": "${{ steps.normalize-branch-name.outputs.normalized-branch-name }}"}}'
