name: Remove QA Slot
run-name: Remove the QA environment for this version 🔬

on:
  pull_request:
    types: [closed]

env:
  SERVICE_URL: https://tool-endpoint.staffr.net/tools-bot/command
  PARAM_TOKEN: f9CiRWUdsxuLp2II0lzkeVsR # hard-coded token in https://github.com/TrackTik/tool-endpoints
  PARAM_COMMAND: "/qaremove"
  PARAM_TEXT: ${{ github.head_ref }}
  # FIXME: AWX will flag the job as failed even though the slot is created
  PARAM_USER_ID: "" # N/A, when triggered via Slack services notifies the user

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Request the service to remove the QA environment for this version
        if: contains(github.event.pull_request.labels.*.name, 'QA Required') # we don't care if the PR is draft or not
        run: |
          curl --location "$SERVICE_URL" \
               --header 'Content-Type: application/x-www-form-urlencoded' \
               --data-urlencode "user_id=$PARAM_USER_ID" \
               --data-urlencode "token=$PARAM_TOKEN" \
               --data-urlencode "command=$PARAM_COMMAND" \
               --data-urlencode "text=$PARAM_TEXT"